CREATE TABLE usuario (
    id_usuario INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role ENUM('ROLE_MEDICO', 'ROLE_ENFERMEIRO', 'ROLE_PACIENTE') NOT NULL
);